### ISSUE TITLE
Disconnecting Player in idle-state?

### ISSUE THREAD

**Issue by dassaffe** [TheZ3ro/pkmngo-map#11]
GitHub issues are for bug reporting and feature requests.  
For general support, comment [on reddit](https://www.reddit.com/r/pokemongodev/comments/4tkt8y/wip_pkmngo_map_merge_all_pythonproject_feature/).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Reddit.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Ubuntu 12.04

Installed version of Python:
2.7.6

### Steps to reproduce
1. run the manage.py script
2. Start the server
3. Head to the web-adress and wait

In the first 10 mins (or so) all pokemon are updated correctly. After a short period of time however, no new spawns are shown (unless you restart the manage.py script). 

What is causing this issue? Someone else having that problem? Using PTC to login.

**Comment by TheZ3ro** [comment]
There is no manage.py in this project

**Comment by minthat** [comment]
Uh... What manage.py? Are you actually referring to the api timeout error that occurs exactly 30 minutes after starting the script? If so, please close this issue and look at the open case.

**Comment by TheZ3ro** [comment]
See this https://github.com/TheZ3ro/pkmngo-map/issues/2
