### ISSUE TITLE
I have a little problem

### ISSUE THREAD

**Issue by CapitanPol** [TheZ3ro/pkmngo-map#17]
well look to tell
See the bug is that when I go to enter 127.0.0.1:8000, I load the map for 1 second and then stops working I catch, and that failure can not be.
I followed the steps at the foot of the letra.y look at the link I leave and I get no error.
if you are so kind to answer

Gyazo:https://gyazo.com/7712374eb8d2d1985ab4cc4fbb68ece0

**Comment by scarecr0w12** [comment]
Looks like because you are using a google Maps Java API that is not allowed to be used where you are running. Create a Google maps Javascript SDK API for a Server, Grap the API it gives, and pop it into the file "Config.json"

**Comment by CapitanPol** [comment]
map api is well in my country is Spain, in fact probe and another way of seeing the Pokemons I think it's called pogo or something and that works for me with the api I have now. whether you think it's not that

**Comment by scarecr0w12** [comment]
You have to put the Google maps api into the configuration, that's why you have that message, your country doesn't matter.
