### ISSUE TITLE
User should be able to copy to clipboard the lat / long of pokemons. Or at least select the text.

### ISSUE THREAD

**Issue by brisc** [TheZ3ro/pkmngo-map#5]

**Comment by minthat** [comment]
Or even better: clicking on the coordinates should launch google maps to that location!

**Comment by TheZ3ro** [comment]
There isn't a standard clipboard JavaScript api working cross browsers. I will try some tests with clipboard.js.

Opening google maps isn't a bad idea but may consume bandwith on mobile phone

**Comment by minthat** [comment]
Here's the usage scenario I see:
You have the scanner running on a server which you access using your phone to connect to the python http server.  While the page is displayed on your mobile phone you'd like gmaps to open when you select a coordinate.

**Comment by brisc** [comment]
latest chrome / firefox is enough . Another scenario is to load the lat / long into fake gps apps directly.

**Comment by TheZ3ro** [comment]
I don't think it's possible to load location directly into fake gps app (on android app need Intent or UrlProvider)

**Comment by minthat** [comment]
What did you mean by lastest chrome / firefox is enough?

I'm thinking that a button could be added to the pokemon info pop-up (or overlayed on top of the co-ordinates) which launches gmaps on mobile devices.

**Comment by TheZ3ro** [comment]
In the next version I will make the pokemon on the map also clickable to show the dialog (https://github.com/TheZ3ro/pkmngo-map/issues/7) and in the dialog/infowindow I will place a button to copy Lat/Long/Time of that pokemon and eventually a button to open google maps

**Comment by brisc** [comment]
That will work

**Comment by TheZ3ro** [comment]
Done with https://github.com/TheZ3ro/pkmngo-map/commit/524a42391450fef7ba2e4d8e60f2399a83c21cc5

Clicking on a pokemon copy its location (I had problem with showing a button in the InfoWindow)
