### ISSUE TITLE
Localhost:8000 blank

### ISSUE THREAD

**Issue by clockw1ze** [TheZ3ro/pkmngo-map#8]
When i open the localhost:8000 in my browser i see the map with pokemon but immediately i get a blank screen with the error "Oops something has gone wrong. Googlemaps could not be loaded see javascript console" for technical details.

Any idea where it  goes wrong?

**Comment by Drawer** [comment]
Did you supply a valid Google Maps API key in the config.json file?

**Comment by clockw1ze** [comment]
I think so yes, i have to select a browser API key or something else? I tried with IOS Api key too but that didnt seem to work

**Comment by Drawer** [comment]
Yes, you need to select a valid browser API key from https://console.developers.google.com/apis/credentials

**Comment by clockw1ze** [comment]
That's what I did. I don't have to change anything else in the json file right?

**Comment by Drawer** [comment]
Nope. Check your developer console in Chrome, hit F12. The error should be better explained over there.

**Comment by clockw1ze** [comment]
I keep getting the same error. Weird..
Do I have to enter something in the referrers box?

![screen shot 2016-07-20 at 08 55 14](https://cloud.githubusercontent.com/assets/12023043/16977657/ba4cdcca-4e57-11e6-9fc1-b4dc4f528f85.png)

**Comment by clockw1ze** [comment]
In the developers console it says:

**Google Maps API error: ApiNotActivatedMapError** in red

**Comment by Drawer** [comment]
https://console.developers.google.com/apis/api/maps_backend/overview
Go over here and click 'enable'.

**Comment by clockw1ze** [comment]
Yes now it works! thanks alot!

**Comment by clockw1ze** [comment]
Can I also increase the "range"?

**Comment by Drawer** [comment]
That is a totally other question. I suggest you make a new issue with a clear question and what you've tried so far by looking at the code and changing some parameters. This keeps the issue tracker for this project clean and searchable for future reference.

**Comment by clockw1ze** [comment]
Alright thanks!

**Comment by TheZ3ro** [comment]
I'm closing the issue since it's resolved
